apiVersion: v2
name: prometheus-stack
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - prometheus
  - alertmanager
  - grafana
  - node-exporter
  - push-gateway

maintainers:
  - name: junwhanChoi
    email: paul911014@gmail.com
