{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: alertmanager
  type: {{ .Values.alertmanager.type }}
  ports:
    - port: 9093
      targetPort: 9093
{{- end}}