{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: grafana
  type: {{ .Values.grafana.service.type }}
{{- end }}
