{{- if .Values.nodeexporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: {{ .Values.namespace }}
  labels:
    name: node-exporter
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        name: node-exporter
        app: node-exporter
      annotations:
        prometheus.io/scrape: "true"
    spec:
      {{- if .Values.global.tolerations }}
      tolerations:
        {{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.nodeexporter.image.name }}:{{ .Values.nodeexporter.image.tag }}
          imagePullPolicy: {{ .Values.nodeexporter.image.policy }}
          name: node-exporter
          ports:
            - containerPort: 9100
              protocol: TCP
              name: http
{{- end}}