{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus-server
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: 9090
      targetPort: 9090
{{- end}}